### ISSUE TITLE
when is v1.1?

### ISSUE THREAD

**Issue by 25HoursaDay** [ReedGraf/anti-pointer-lock-bypass#1]
im sorry to bug you but when do you think v1.1 will be done?

**Comment by ReedGraf** [comment]
I'm not exactly sure, I want to release it with something else so it isn't standalone but I haven't had much time lately with school. I'll be sure to keep you informed on this thread. Thanks! :D

**Comment by ReedGraf** [comment]
Version 1.1 is now released. Download it from the releases.
